apps:
  - name: 1Password
    cask: 1password
    dock:
      state: present
      pos: 7
    path: "/Applications/1Password.app"
  - name: App Store
    dock:
      state: present
      pos: 2
    path: "/Applications/App Store.app" 
  - name: Brave Browser
    cask: brave-browser
    dock:
      state: present
      pos: 3
    path: "/Applications/Brave Browser.app"     
  - name: Dropbox
    cask: dropbox
    dock: 
      state: absent
    path: "/Applications/Dropbox.app"
  - name: GitHub Desktop
    cask: github
    dock:
      state: present
      pos: 5
    path: "/Applications/GitHub Desktop.app"
  - name: Google Chrome
    dock: 
      state: absent
    path: "/Applications/Google Chrome.app"     
  - name: Messages
    dock:
      state: present
      pos: 1
    path: "/Applications/Messages.app"
  - name: Sonos
    cask: sonos
    dock: 
      state: present
      pos: 7
    path: "/Applications/Sonos.app"
  - name: Tabby
    cask: tabby
    dock: 
      state: present
      pos: 4
    path: "/Applications/Utilities/Tabby.app"    
  - name: Visual Studio Code
    cask: visual-studio-code
    dock: 
      state: present
      pos: 6
    path: "/Applications/Visual Studio Code.app"
  - name: VLC
    cask: vlc
    dock: 
      state: absent
    path: "/Applications/VLC.app"
  - name: WhatsApp
    cask: whatsapp
    dock: 
      state: absent
    path: "/Applications/WhatsApp.app"    
  - name: Adobe Acrobat Reader DC
    dock:
      state: absent     
  - name: BlueJeans
    dock:
      state: absent         
  - name: Calendar
    dock:
      state: absent      
  - name: Contacts
    dock:
      state: absent 
  - name: FaceTime
    dock:
      state: absent      
  - name: Freeform
    dock:
      state: absent
  - name: Keynote
    dock:
      state: absent      
  - name: Launchpad
    dock:
      state: absent      
  - name: Mail
    dock:
      state: absent        
  - name: Managed Software Center
    dock:
      state: absent  
  - name: Maps
    dock:
      state: absent      
  - name: Music
    dock:
      state: absent
  - name: News
    dock:
      state: absent
  - name: Notes
    dock:
      state: absent         
  - name: Numbers
    dock:
      state: absent
  - name: Pages
    dock:
      state: absent
  - name: Photos
    dock:
      state: absent
  - name: Red Hat Printer Setup
    dock:
      state: absent  
  - name: Red Hat Mac Info
    dock:
      state: absent  
  - name: Reminders
    dock:
      state: absent      
  - name: Safari
    dock:
      state: absent      
  - name: System Preferences
    dock:
      state: absent 
  - name: Terminal
    dock: 
      state: absent      
  - name: TV
    dock:
      state: absent      
