do_homebrew_update:     yes

homebrew_repo:          https://github.com/Homebrew/brewß
homebrew_prefix:        /opt
homebrew_install_path:  "{{ homebrew_prefix }}/homebrew"
homebrew_brew_bin_path: "{{ homebrew_prefix }}/bin"
