# roles/richmitch_mac/tasks/defaults.yml
- name: Get current Terminal profile.
  shell: defaults read com.apple.Terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false

- name: Ensure custom Terminal profile is added.
  shell: open "files/Default Settings.terminal"
  changed_when: false
  when: "'Basic' not in terminal_theme.stdout"

- name: Ensure custom Terminal profile is set as default.
  shell: "{{ item }}"
  with_items:
    - defaults write com.apple.Terminal 'Default Window Settings' -string 'Basic'
    - defaults write com.apple.Terminal 'Startup Window Settings' -string 'Basic'
  changed_when: false
  when: "'Basic' not in terminal_theme.stdout"
