# roles/richmitch_mac/tasks/main.yml
---
- { include: homebrew.yml,  tags: "homebrew", when: do_homebrew_setup|bool }

- { include: packages.yml,  tags: "packages", when: do_homebrew_packages|bool }
- { include: casks.yml,     tags: "casks",    when: do_homebrew_casks|bool }
  
- name: Tidy things up how I like them
  import_tasks: tidy.yml
  when: do_tidy

- name: Set app defaults
  import_tasks: app-defaults.yml
  when: do_appdefaults
