# roles/richmitch_mac/tasks/tidy.yml
---
- name: Cleanup the Dock
  shell: dockutil --remove '{{ item }}'
  ignore_errors: true
  with_items: '{{ dockitems_to_remove }}'

- name: Add items to Dock if they don't exist
  shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
  with_items: '{{ dockitems_to_persist }}'

- name: Fix Dock item order
  shell: dockutil --move '{{ item.name }}' --position {{ item.pos }}
  with_items: '{{ dockitems_to_persist }}'

- name: Set mouse tracking speed
  shell: defaults write -g com.apple.mouse.scaling '{{ default_mouse_tracking }}'