do_homebrew_setup:    no
do_homebrew_packages: yes
do_homebrew_casks:    yes
do_dock:              yes
do_hot_corners:       yes
do_osx_defaults:      yes
do_app_defaults:      yes
do_network:           yes
