# roles/richmitch_mac/vars/main.yml

do_update_homebrew: no

do_installs: false
do_tidy: true
do_appdefaults: false

homebrew_packages:
- maven
- openjdk

apps:
  - name: Adobe Acrobat Reader DC
    dock:
      state: absent
  - name: App Store
    dock:
      state: present
      pos: 2
    path: "/Applications/App Store.app"
  - name: BlueJeans
    dock:
      state: absent    
  - name: Brave Browser
    cask: brave-browser
    dock:
      state: present
      pos: 3
    path: "/Applications/Brave Browser.app"
  - name: Calendar
    dock:
      state: absent
  - name: Contacts
    dock:
      state: absent      
  - name: Dropbox
    cask: dropbox
    dock: 
      state: absent
    path: "/Applications/Dropbox.app"
  - name: Facetime
    dock:
      state: absent
  - name: GitHub Desktop
    cask: github
    dock:
      state: present
      pos: 5
    path: "/Applications/GitHub Desktop.app"
  - name: Google Chrome
    cask: google-chrome
    dock: 
      state: absent
    path: "/Applications/Google Chrome.app"
  - name: iBooks
    dock:
      state: absent
  - name: iTunes
    dock:
      state: absent
  - name: Keynote
    dock:
      state: absent
  - name: Launchpad
    dock:
      state: absent
  - name: Mail
    dock:
      state: absent
  - name: Managed Software Center
    dock:
      state: absent
  - name: Maps
    dock:
      state: absent      
  - name: Messages
    dock:
      state: present
      pos: 1
    path: "/Applications/Messages.app"
  - name: Microsoft Teams
    cask: microsoft-teams
    dock:
      state: absent
    path: "/Applications/Microsoft Teams.app"
  - name: News
    dock:
      state: absent
  - name: Notes
    dock:
      state: absent
  - name: Numbers
    dock:
      state: absent
  - name: Pages
    dock:
      state: absent
  - name: Photos
    dock:
      state: absent      
  - name: Postman
    cask: postman
    dock:
      state: absent
    path: "/Applications/Postman.app"
  - name: Reminders
    dock:
      state: absent
  - name: Safari
    dock:
      state: absent      
  - name: System Preferences
    dock:
      state: absent
  - name: Sonos
    cask: sonos
    dock: 
      state: present
      pos: 7
    path: "/Applications/Sonos.app"
  - name: Terminal
    dock: 
      state: present
      pos: 4
    path: "/Applications/Utilities/Terminal.app"
  - name: TV
    dock:
      state: absent
  - name: Virtual Box
    cask: virtualbox
    dock:
      state: absent
    path: "/Applications/VirtualBox.app"
  - name: Visual Studio Code
    cask: visual-studio-code
    dock: 
      state: present
      pos: 6
    path: "/Applications/Visual Studio Code.app"
  - name: VLC
    cask: vlc
    dock: 
      state: absent
    path: "/Applications/VLC.app"
  - name: WhatsApp
    cask: whatsapp
    dock: 
      state: absent
    path: "/Applications/WhatsApp.app"

install_fonts:
  - name: "Red Hat Fonts"
    cask: font-redhat

mac_default_settings:
  - name: Mouse tracking speed
    domain: -g
    key: com.apple.mouse.scaling
    type: float
    value: 5.0
  - name: Scroll direction
    domain: -g
    key: com.apple.swipescrolldirection
    type: bool
    value: true
  - name: Dock orientation
    domain: 
    key: com.apple.dock orientation
    type: string
    value: bottom
  - name: Dock size
    domain: 
    key: com.apple.dock largesize
    type: string
    value: 90
  - name: Dock autohide
    domain: 
    key: com.apple.dock autohide
    type: string
    value: true
  - name: Finder preferred view style
    domain: 
    key: com.apple.finder FXPreferredViewStyle
    type: string
    value: Nlsv
  - name: Finder preferred Group By
    domain: 
    key: com.apple.finder FXPreferredGroupBy
    type: string
    value: "Date Modified"
  - name: Finder arrange Group By
    domain: 
    key: com.apple.finder FXArrangeGroupViewBy
    type: string
    value: "Date Modified"